export const ProductData = [
    {
      id: 1,
      title: "Shoes",
      url: "https://5.imimg.com/data5/SELLER/Default/2023/2/RD/LE/FP/184929171/bruton-shoes-for-exclusive-trendy-casual-sports-shoes-for-men-running-shoes-for-men-black-red--500x500.jpg",
      name: "TRQ Shoes",
      category: "Shoes",
      seller: "AMZ",
      price: 1999,
    },
    {
      id: 2,
      title: "Digital Watch",
      url: "https://importedgear.pk/cdn/shop/files/1686858773689.png?v=1686858725&width=600",
      name: "TRQ Digital Watch",
      category: "DigitalWatch",
      seller: "AMZ",
      price: 2599,
    },
    {
      id: 3,
      title: "Laptop",
      url: "https://www.hp.com/us-en/shop/app/assets/images/uploads/prod/HP%20Pavilion%20Laptop%20151680104202881838.jpg?impolicy=prdimg&imdensity=1&imwidth=600",
      name: "TRQ Laptop",
      category: "Laptop",
      seller: "AMZ",
      price: 29999,
    },
    {
      id: 4,
      title: "Security Camera",
      url: "https://www.agri-linc.com/media/catalog/product/h/a/ha501951_1.png?optimize=low&bg-color=255,255,255&fit=bounds&height=470&width=600&canvas=600:470&format=jpeg",
      name: "TRQ Security Camera",
      category: "SecurityCamera",
      seller: "AMZ",
      price: 7999,
    },
    {
      id: 5,
      title: "Watch",
      url: "https://doxawatches.com/cdn/shop/files/aquamarine-833412.jpg?v=1717526653&width=1881",
      name: "TRQ Watch",
      category: "Watch",
      seller: "AMZ",
      price: 13999,
    },
    {
      id: 6,
      url: "https://nestasia.in/cdn/shop/files/Greencoffeemugs_1.jpg?v=1699363178&width=600",
      name: "TRQ Mug",
      category: "Mug",
      seller: "AMZ",
      price: 3599,
    },
    {
      id: 7,
      url: "https://www.gizmochina.com/wp-content/uploads/2018/11/Guophone-X3-400x400.jpg",
      name: "TRQ Mobile",
      category: "Mobile",
      seller: "AMZ",
      price: 19999,
    },
    {
      id: 8,
      url: "https://m.media-amazon.com/images/I/61qF2lNCIHL.jpg",
      name: "TRQ Mobile Charger",
      category: "Mobile Charger Black Color",
      seller: "AMZ",
      price: 599,
    },
    {
      id: 9,
      url: "https://m.media-amazon.com/images/I/6176+zi7I2L._AC_UF1000,1000_QL80_.jpg",
      name: "TRQ Mobile Charger",
      category: "Mobile Charger White Color",
      seller: "AMZ",
      price: 599,
    },
    {
      id: 10,
      url: "https://images.cnbctv18.com/wp-content/uploads/2024/02/honor-magic-6-pro.jpeg?impolicy=website&width=400&height=300",
      name: "TRQ Mobile",
      category: "Mobile",
      seller: "AMZ",
      price: 25999,
    },
  ]